apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "agentoe-vbgw.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "agentoe-vbgw.labels" . | nindent 4 }}
data:
  {{- range $k, $v := .Values.config }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
