{{- if .Values.externalSecrets.enabled -}}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "agentoe-vbgw.fullname" . }}-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "agentoe-vbgw.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval | quote }}
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStoreRef.name }}
    kind: {{ .Values.externalSecrets.secretStoreRef.kind }}
  target:
    name: {{ include "agentoe-vbgw.fullname" . }}-secrets
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      type: Opaque
      metadata:
        labels:
          {{- include "agentoe-vbgw.labels" . | nindent 10 }}
  data:
    {{- range .Values.externalSecrets.data }}
    - secretKey: {{ .secretKey | quote }}
      remoteRef:
        key: "{{ $.Values.externalSecrets.secretsPrefix }}/{{ .remoteKey }}"
        {{- if .property }}
        property: {{ .property | quote }}
        {{- end }}
    {{- end }}
{{- end }}
